name: ProxyStore

channels:
    - defaults
    - conda-forge

dependencies:
    - python>=3.7.*
    - pip
    - virtualenv
    - redis
    - pip:
        - -e .
        - -r requirements-dev.txt
        - -r docs/requirements.txt
        - funcx
        - funcx_endpoint
