site_name: ProxyStore
site_url: https://proxystore.dev
site_author: Globus Labs
site_description: Documentation for ProxyStore.

repo_name: proxystore/proxystore
repo_url: https://github.com/proxystore/proxystore

copyright: Copyright &copy; 2021—Present by <a target="_blank" href="https://gregpauloski.com">Greg Pauloski</a> and <a target="_blank" href="https://labs.globus.org">Globus Labs</a>


theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Open Sans
    code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: deep purple
      accent: lime
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  overrides: docs/_overrides
  # favicon: static/favicon.png
  # icon:
  #   logo: logo

watch:
  - mkdocs.yml
  - README.md
  - docs/
  - proxystore/

extra:
  version:
    default: latest
    provider: mike

extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: proxystore
      repo: proxystore
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home:
      - home/index.md
      - Installation: home/installation.md
      - Get Started: home/get-started.md
      - Examples: home/examples.md
      - Known Issues: home/known-issues.md
      - Changelog (GitHub): https://github.com/proxystore/proxystore/releases
  - Concepts:
      - concepts/index.md
      - Proxy: concepts/proxy.md
      - Connector: concepts/connector.md
      - Store: concepts/store.md
  - Guides:
      - guides/index.md
      - Endpoints: guides/endpoints.md
      - Performance: guides/performance.md
  - API Reference: api/
  - Contributing:
      - contributing/index.md
      - Style Guide: contributing/style-guide.md
      - Issues and Pull Requests: contributing/issues-pull-requests.md
      - Releases: contributing/releases.md

plugins:
  - gen-files:
      scripts:
        - docs/generate_api.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      custom_templates: docs/_templates
      enable_inventory: true
      handlers:
        python:
          setup_commands:
            - import pytkdocs_tweaks
            - pytkdocs_tweaks.main()
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_section_style: list
            docstring_style: google
            inherited_members: yes
            line_length: 60
            members_order: source
            merge_init_into_class: yes
            separate_signature: yes
            # Mutually exclusive with separate_signature
            # show_root_members_full_path: yes
            # Causes black error with show_root_full_path
            # show_object_full_path: yes
            show_root_full_path: yes
            show_signature_annotations: yes
            show_submodules: no
  - search
  - section-index
