# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base

    - name: Lint with black
      run: |
        black --check proxystore
        black --check examples
        black --check setup.py

    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics

    - name: Test with pytest
      run: |
        pytest --cov=proxystore --ignore proxystore/store/test/test_globus.py proxystore

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
      if: matrix.python-version == '3.7'
