name: integration

on:
  push:
    branches: [main]
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  dim:
    timeout-minutes: 10

    strategy:
      matrix:
        include:
        - python: 3.7
          toxenv: py37
        - python: 3.8
          toxenv: py38
        - python: 3.9
          toxenv: py39
        - python: '3.10'
          toxenv: py310

    runs-on: ubuntu-latest

    steps:
      - name: Checkout v2
        # Required to mount the Github Workspace to a volume
        uses: actions/checkout@v2

      - name: Pull image and run tests
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          image: ghcr.io/proxystore/proxystore-dim:nightly
          options: -v ${{ github.workspace }}:/proxystore --network host --workdir /proxystore
          run: tox -e ${{ matrix.toxenv }}-dim
