name: main

on:
  push:
    branches: [main]
  pull_request:

jobs:
  main:
    strategy:
      matrix:
        include:
        # linux
        - os: ubuntu-latest
          python: 3.6
          toxenv: python3.6
        - os: ubuntu-latest
          python: 3.7
          toxenv: python3.7
        - os: ubuntu-latest
          python: 3.8
          toxenv: python3.8
        - os: ubuntu-latest
          python: 3.9
          toxenv: python3.9
        - os: ubuntu-latest
          python: '3.10'
          toxenv: python3.10
        # windows
        - os: windows-latest
          python: 3.9
          toxenv: python3.9
        # misc
        - os: ubuntu-latest
          python: 3.9
          toxenv: flake8
        - os: ubuntu-latest
          python: 3.9
          toxenv: pre-commit
        - os: ubuntu-latest
          python: 3.9
          toxenv: docs
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Packages
        run: python -mpip install --upgrade setuptools pip tox virtualenv

      - name: Run Tox
        run: tox -e ${{ matrix.toxenv }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
        if: matrix.python == '3.9'
