name: style

on: [push, pull_request]

jobs:
  style:

    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          python: 3.9
          toxenv: flake8
        - os: ubuntu-latest
          python: 3.9
          toxenv: pre-commit
        - os: ubuntu-latest
          python: 3.9
          toxenv: docs
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Packages
        run: python -mpip install --upgrade setuptools pip tox virtualenv

      - name: Run Tox
        run: tox -e ${{ matrix.toxenv }}
