name: tests

on:
  push:
    branches: [main]
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    timeout-minutes: 10

    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          python: 3.7
          toxenv: py37
        - os: ubuntu-latest
          python: 3.8
          toxenv: py38
        - os: ubuntu-latest
          python: 3.9
          toxenv: py39
        - os: ubuntu-latest
          python: '3.10'
          toxenv: py310
        - os: macos-latest
          python: '3.10'
          toxenv: py310
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Packages
        run: python -mpip install --upgrade setuptools pip tox virtualenv

      - name: Run Tox
        run: tox -e ${{ matrix.toxenv }}

      - name: Check if ~/.proxystore created
        uses: andstor/file-existence-action@v2
        with:
          files: "~/.proxystore"

      - name: Fail if ~/.proxystore created
        if: steps.check_files.outputs.file_exists == 'true'
        run: echo "Test suite created ~/.proxystore when it shouldn't!" && false
