name: tests

on: [push, pull_request]

jobs:
  tests:

    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          python: 3.7
          toxenv: python3.7
        - os: ubuntu-latest
          python: 3.8
          toxenv: python3.8
        - os: ubuntu-latest
          python: 3.9
          toxenv: python3.9
        - os: ubuntu-latest
          python: '3.10'
          toxenv: python3.10
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Packages
        run: python -mpip install --upgrade setuptools pip tox virtualenv

      - name: Run Tox
        run: tox -e ${{ matrix.toxenv }}
